import { defineConfig } from 'vite-plus';

// Root Vite+ workspace config. Per-package configs live in each package and
// inherit/override these defaults. See https://viteplus.dev/guide/
export default defineConfig({
	staged: {
		'*': 'vp check --fix',
		// docs/configuration.md and the deployment-wizard snapshots are generated
		// from the config registry (packages/config/src/spec.ts) — fail the commit
		// when they drift instead of finding out in CI.
		'packages/config/src/**':
			"bash -c 'pnpm --filter @marimo-hub/config test && pnpm --filter @marimo-hub/docs test'",
		'docs/configuration.md': "bash -c 'pnpm --filter @marimo-hub/config test'",
		'docs/partials/integrations/**': "bash -c 'pnpm --filter @marimo-hub/docs test'",
		'apps/docs/.vitepress/wizard/**': "bash -c 'pnpm --filter @marimo-hub/docs test'",
	},
	fmt: {
		useTabs: true,
		singleQuote: true,
	},
	lint: {
		plugins: [
			'react',
			'react-hooks',
			'react-perf',
			'typescript',
			'unicorn',
			'oxc',
			'jsx-a11y',
			'import',
		],
		options: {
			typeAware: true,
		},
		categories: {
			correctness: 'error',
		},
		env: {
			builtin: true,
			browser: true,
		},
		// `schema.ts` is generated by openapi-typescript; linting it would lose fixes
		// on every regen and re-flag generated index signatures.
		ignorePatterns: [
			'dist',
			'node_modules',
			'vendor',
			'**/ts-reset.d.ts',
			'packages/client/src/schema.ts',
		],
		rules: {
			'eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
			'react/react-in-jsx-scope': 'off',

			// --- consistency + bug-catchers (added) ---
			'eslint/eqeqeq': ['error', 'always', { null: 'ignore' }],
			'eslint/prefer-const': 'error',
			'eslint/prefer-template': 'error',
			'eslint/no-console': ['error', { allow: ['warn', 'error'] }],

			'typescript/no-explicit-any': 'error',
			'typescript/array-type': ['error', { default: 'array' }],

			// --- async safety (type-aware) ---
			'typescript/no-floating-promises': 'error',
			'typescript/no-misused-promises': 'error',
			'typescript/await-thenable': 'error',
			'typescript/return-await': ['error', 'in-try-catch'],

			'typescript/consistent-type-imports': 'error',
			'typescript/no-import-type-side-effects': 'error',
			'typescript/only-throw-error': 'error',
			'typescript/switch-exhaustiveness-check': 'error',
			// String arrays are exempt: their default lexicographic sort is already correct.
			'typescript/require-array-sort-compare': ['error', { ignoreStringArrays: true }],
			'typescript/no-deprecated': 'error',

			'unicorn/prefer-node-protocol': 'error',
			'unicorn/throw-new-error': 'error',
			'unicorn/prefer-string-replace-all': 'error',
			'unicorn/prefer-optional-catch-binding': 'error',

			// `unbound-method` false-positives on our namespace-helper pattern
			// (passing `this`-less functions like `ProjectId.is`/`SandboxId.create`
			// as callbacks), so it adds noise without catching real `this` loss.
			'typescript/unbound-method': 'off',

			// --- additional consistency + cleanup (batch 2) ---
			// NB: `prefer-nullish-coalescing` was evaluated and rejected — our `||`
			// fallbacks are intentional (empty-string/0 should fall through to the
			// default), so `??` would change behavior. Don't re-add it.
			'typescript/prefer-optional-chain': 'error',
			'typescript/no-unnecessary-type-assertion': 'error',
			// Force object literals to be validated by annotation, not branded past the
			// checker with `{ … } as T` (which silently allows missing/excess props).
			// `allow-as-parameter` still permits the OpenAPI doc-gen stub passed as an arg.
			'typescript/consistent-type-assertions': [
				'error',
				{ assertionStyle: 'as', objectLiteralTypeAssertions: 'allow-as-parameter' },
			],
			'typescript/no-unnecessary-boolean-literal-compare': 'error',
			'typescript/dot-notation': 'error',
			'eslint/object-shorthand': 'error',
			'eslint/no-unneeded-ternary': 'error',
			'eslint/no-else-return': 'error',
			'unicorn/prefer-number-properties': 'error',
			'unicorn/no-lonely-if': 'error',
			'unicorn/prefer-array-some': 'error',
			'unicorn/prefer-includes': 'error',
			'unicorn/prefer-string-slice': 'error',
			'unicorn/prefer-date-now': 'error',
			'unicorn/explicit-length-check': 'error',
			'unicorn/no-instanceof-array': 'error',
			'react/jsx-no-useless-fragment': 'error',
			'react/no-array-index-key': 'error',

			// --- autofixable style cleanups (batch 3) ---
			'react/self-closing-comp': 'error',
			'react/jsx-boolean-value': 'error',
			'react/jsx-curly-brace-presence': ['error', { props: 'never', children: 'never' }],
			'typescript/consistent-indexed-object-style': 'error',
			'typescript/prefer-for-of': 'error',
			'typescript/no-inferrable-types': 'error',
			// `checkArguments` strips explicit `undefined` from call sites, which
			// breaks calls to params typed `T | undefined` (not optional) and erases
			// deliberate test intent (`fn(undefined)`), so only clean returns/defaults.
			'unicorn/no-useless-undefined': ['error', { checkArguments: false }],
			'unicorn/prefer-string-starts-ends-with': 'error',
			'unicorn/prefer-regexp-test': 'error',
			'unicorn/prefer-array-flat': 'error',
			'unicorn/prefer-logical-operator-over-ternary': 'error',
			'unicorn/prefer-modern-math-apis': 'error',
			// NB: `text-encoding-identifier-case` was evaluated and rejected — it
			// rewrites `'utf-8'` to `'utf8'`, but `SandboxInstance.readFile` passes the
			// vendor-reported encoding straight through and the Cloudflare sandbox SDK
			// emits `'utf-8'`, so normalizing it breaks that boundary type. Don't re-add it.

			// --- react hooks correctness (packages/web) ---
			'react-hooks/rules-of-hooks': 'error',
			'react-hooks/exhaustive-deps': 'warn',
			'react/no-unstable-nested-components': 'error',

			// --- imports / architecture ---
			'import/no-cycle': 'error',
			'import/no-duplicates': 'error',
			'import/no-self-import': 'error',
			'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],

			// --- accessibility (jsx-a11y) ---
			// These two ban clickable non-interactive elements
			// (`<div onClick={navigate()}>`), which break cmd/middle-click and
			// keyboard activation. Use `RowLink`/`Button` instead.
			'jsx-a11y/click-events-have-key-events': 'error',
			'jsx-a11y/no-static-element-interactions': 'error',
			'jsx-a11y/no-noninteractive-element-interactions': 'error',
			'jsx-a11y/anchor-is-valid': 'error',
			'jsx-a11y/anchor-has-content': 'error',
			'jsx-a11y/control-has-associated-label': 'error',
			'jsx-a11y/label-has-associated-control': 'error',
			'jsx-a11y/heading-has-content': 'error',
			'jsx-a11y/alt-text': 'error',
			'jsx-a11y/iframe-has-title': 'error',
			'jsx-a11y/autocomplete-valid': 'error',
			'jsx-a11y/aria-props': 'error',
			'jsx-a11y/aria-proptypes': 'error',
			'jsx-a11y/aria-role': 'error',
			'jsx-a11y/aria-unsupported-elements': 'error',
			'jsx-a11y/role-has-required-aria-props': 'error',
			'jsx-a11y/no-aria-hidden-on-focusable': 'error',
			// `autoFocus` on a modal dialog's first field is intentional here, so this
			// rule is off rather than per-dialog overrides.
			'jsx-a11y/no-autofocus': 'off',
		},
		overrides: [
			{
				// Tests and test helpers may use `any`, log freely, and stringify/spread
				// mock objects (URLs, fake records) where these type-aware rules would
				// otherwise false-positive.
				files: ['**/*.test.ts', '**/*.test.tsx', '**/testing/**'],
				rules: {
					'typescript/no-explicit-any': 'off',
					'eslint/no-console': 'off',
					'typescript/no-base-to-string': 'off',
					'typescript/no-misused-spread': 'off',
					// Async functions are routinely passed to `vi.spyOn(...).mockImplementation`
					// for methods (e.g. S3 `send`) whose callback overload types the impl as
					// void-returning, so this rule false-positives on correct async mocks.
					'typescript/no-misused-promises': 'off',
					// Test doubles assert minimal object literals to SDK types on purpose.
					'typescript/consistent-type-assertions': 'off',
				},
			},
			{
				// Entrypoints, examples, and dedicated logging modules write to stdout.
				files: ['apps/server/**', 'examples/**', 'scripts/**', '**/log.ts'],
				rules: {
					'eslint/no-console': 'off',
				},
			},
			{
				files: ['packages/core/**', 'packages/api/**'],
				rules: {
					'no-restricted-imports': [
						'error',
						{
							patterns: [
								'@marimo-hub/storage-*',
								'@marimo-hub/compute-*',
								'@marimo-hub/auth-*',
								'@marimo-hub/credentials-*',
							],
						},
					],
				},
			},
		],
	},
	// This `test` block governs ONLY the root-level `vp test` run that
	// `pnpm test:coverage` invokes — it is NOT inherited by the per-package
	// `vp run -r test` (`pnpm test`) runs, which use each package's own config.
	// `packages/web` is excluded here because its `@/` path aliases resolve only
	// under its own vite config; cover it with `pnpm --filter @marimo-hub/web
	// test --coverage`.
	test: {
		exclude: ['**/node_modules/**', '**/dist/**', 'packages/web/**', 'apps/e2e/**'],
		coverage: {
			provider: 'v8',
			reporter: ['text', 'html'],
			exclude: [
				'**/*.test.ts',
				'**/*.test.tsx',
				'**/testing/**',
				'**/dist/**',
				'**/*.config.{ts,js}',
				'**/*.d.ts',
			],
		},
	},
	run: {
		cache: true,
	},
});
