import { defineConfig } from 'vite-plus';

// Root Vite+ workspace config. Per-package configs live in each package and
// inherit/override these defaults. See https://viteplus.dev/guide/
export default defineConfig({
	staged: {
		'*': 'vp check --fix',
		// docs/configuration.md and the deployment-wizard snapshots are generated
		// from the config registry (packages/config/src/spec.ts) — fail the commit
		// when they drift instead of finding out in CI.
		'packages/config/src/**':
			"bash -c 'pnpm --filter @marimo-hub/config test && pnpm --filter @marimo-hub/docs test'",
		'docs/configuration.md': "bash -c 'pnpm --filter @marimo-hub/config test'",
		'docs/partials/integrations/**': "bash -c 'pnpm --filter @marimo-hub/docs test'",
		'apps/docs/.vitepress/wizard/**': "bash -c 'pnpm --filter @marimo-hub/docs test'",
	},
	fmt: {
		useTabs: true,
		singleQuote: true,
	},
	lint: {
		plugins: [
			'react',
			'react-hooks',
			'react-perf',
			'typescript',
			'unicorn',
			'oxc',
			'jsx-a11y',
			'import',
		],
		options: {
			typeAware: true,
		},
		categories: {
			correctness: 'error',
		},
		env: {
			builtin: true,
			browser: true,
		},
		// `schema.ts` is generated by openapi-typescript; linting it would lose fixes
		// on every regen and re-flag generated index signatures.
		ignorePatterns: [
			'dist',
			'node_modules',
			'vendor',
			'**/ts-reset.d.ts',
			'packages/client/src/schema.ts',
		],
		rules: {
			'eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
			'react/react-in-jsx-scope': 'off',

			// --- consistency + bug-catchers ---
			'eslint/eqeqeq': ['error', 'always', { null: 'ignore' }],
			'eslint/prefer-const': 'error',
			'eslint/prefer-template': 'error',
			'eslint/no-console': ['error', { allow: ['warn', 'error'] }],

			'typescript/no-explicit-any': 'error',
			'typescript/array-type': ['error', { default: 'array' }],

			// --- async safety (type-aware) ---
			'typescript/no-floating-promises': 'error',
			'typescript/no-misused-promises': 'error',
			'typescript/await-thenable': 'error',
			'typescript/return-await': ['error', 'in-try-catch'],

			'typescript/consistent-type-imports': 'error',
			'typescript/no-import-type-side-effects': 'error',
			'typescript/only-throw-error': 'error',
			'typescript/switch-exhaustiveness-check': 'error',
			// String arrays are exempt: their default lexicographic sort is already correct.
			'typescript/require-array-sort-compare': ['error', { ignoreStringArrays: true }],
			'typescript/no-deprecated': 'error',

			'unicorn/prefer-node-protocol': 'error',
			'unicorn/throw-new-error': 'error',
			'unicorn/prefer-string-replace-all': 'error',
			'unicorn/prefer-optional-catch-binding': 'error',

			// `unbound-method` false-positives on our namespace-helper pattern
			// (passing `this`-less functions like `ProjectId.is`/`SandboxId.create`
			// as callbacks), so it adds noise without catching real `this` loss.
			'typescript/unbound-method': 'off',

			// --- consistency + cleanup ---
			// `prefer-nullish-coalescing` is intentionally off: our `||` fallbacks on
			// empty-string/0 should fall through to the default, so `??` would change
			// behavior.
			'typescript/prefer-optional-chain': 'error',
			'typescript/no-unnecessary-type-assertion': 'error',
			// Force object literals to be validated by annotation, not branded past the
			// checker with `{ … } as T` (which silently allows missing/excess props).
			// `allow-as-parameter` still permits the OpenAPI doc-gen stub passed as an arg.
			'typescript/consistent-type-assertions': [
				'error',
				{ assertionStyle: 'as', objectLiteralTypeAssertions: 'allow-as-parameter' },
			],
			'typescript/no-unnecessary-boolean-literal-compare': 'error',
			'typescript/dot-notation': 'error',
			'eslint/object-shorthand': 'error',
			'eslint/no-unneeded-ternary': 'error',
			'eslint/no-else-return': 'error',
			'unicorn/prefer-number-properties': 'error',
			'unicorn/no-lonely-if': 'error',
			'unicorn/prefer-array-some': 'error',
			'unicorn/prefer-string-slice': 'error',
			'unicorn/prefer-date-now': 'error',
			'unicorn/explicit-length-check': 'error',
			'unicorn/no-instanceof-array': 'error',
			'react/jsx-no-useless-fragment': 'error',
			'react/no-array-index-key': 'error',

			// --- autofixable style cleanups ---
			'react/self-closing-comp': 'error',
			'react/jsx-boolean-value': 'error',
			'react/jsx-curly-brace-presence': ['error', { props: 'never', children: 'never' }],
			'typescript/consistent-indexed-object-style': 'error',
			'typescript/prefer-for-of': 'error',
			'typescript/no-inferrable-types': 'error',
			// `checkArguments` strips explicit `undefined` from call sites, which
			// breaks calls to params typed `T | undefined` (not optional) and erases
			// deliberate test intent (`fn(undefined)`), so only clean returns/defaults.
			'unicorn/no-useless-undefined': ['error', { checkArguments: false }],
			'unicorn/prefer-regexp-test': 'error',
			'unicorn/prefer-array-flat': 'error',
			'unicorn/prefer-logical-operator-over-ternary': 'error',
			'unicorn/prefer-modern-math-apis': 'error',
			// `text-encoding-identifier-case` is intentionally off: it rewrites
			// `'utf-8'` to `'utf8'`, but `SandboxInstance.readFile` passes the
			// vendor-reported encoding straight through and the Cloudflare sandbox SDK
			// emits `'utf-8'`, so normalizing it breaks that boundary type.

			// --- production hardening ---
			// Injection sinks: no code-from-string, no `javascript:` URLs.
			'eslint/no-eval': 'error',
			'eslint/no-implied-eval': 'error',
			'eslint/no-new-func': 'error',
			'eslint/no-script-url': 'error',

			// `custom-error-definition` requires each error subclass to set `this.name`
			// to its own class name — load-bearing because `isConfigError`/domain
			// dispatch match on `err.name` across module-dup boundaries (see
			// packages/config/src/errors.ts). The rest extend the existing
			// `only-throw-error` guarantee to type-guards and rejected promises.
			'unicorn/error-message': 'error',
			'unicorn/custom-error-definition': 'error',
			'unicorn/prefer-type-error': 'error',
			'unicorn/no-thenable': 'error',
			'unicorn/no-useless-promise-resolve-reject': 'error',
			'typescript/prefer-promise-reject-errors': 'error',

			// A value returned from a `new Promise(executor)` is discarded, and a
			// returned promise's rejection is swallowed. Force a statement body.
			'eslint/no-promise-executor-return': 'error',
			// Reassigning a parameter mutates the caller's object and hides data flow.
			'eslint/no-param-reassign': 'error',
			'eslint/no-return-assign': 'error',
			// `parseInt(x)` without a radix parses `'0x…'`/legacy-octal surprisingly.
			'eslint/radix': 'error',
			'unicorn/prefer-set-has': 'error',

			'typescript/no-unnecessary-template-expression': 'error',
			'typescript/no-meaningless-void-operator': 'error',
			'typescript/no-redundant-type-constituents': 'error',

			// Deferred — valuable, but each needs a case-by-case migration rather
			// than a blanket flip: `no-non-null-assertion` (many `!` sites are safe
			// after a `.has()`/regex guard), `no-unnecessary-condition` (trips on
			// defensive checks at trust boundaries), `no-confusing-void-expression`
			// (mostly `() => setState()` arrows). `no-await-in-loop` stays off: our
			// loops are intentionally sequential (CAS retries, ordered writes).

			// --- correctness + foot-guns ---
			'eslint/no-self-compare': 'error',
			'eslint/no-unmodified-loop-condition': 'error',
			'eslint/no-constructor-return': 'error',
			'eslint/default-case-last': 'error',
			'eslint/no-useless-concat': 'error',
			'eslint/prefer-object-spread': 'error',
			'eslint/symbol-description': 'error',
			'typescript/no-array-delete': 'error',
			'typescript/no-for-in-array': 'error',
			'typescript/no-confusing-non-null-assertion': 'error',
			'typescript/no-unnecessary-parameter-property-assignment': 'error',
			'unicorn/no-negation-in-equality-check': 'error',
			'unicorn/no-useless-fallback-in-spread': 'error',
			'unicorn/no-array-method-this-argument': 'error',
			'unicorn/require-array-join-separator': 'error',
			'unicorn/consistent-existence-index-check': 'error',
			'unicorn/no-single-promise-in-promise-methods': 'error',
			'unicorn/no-await-in-promise-methods': 'error',

			// --- perf / modern APIs ---
			'unicorn/prefer-spread': 'error',
			'unicorn/no-useless-spread': 'error',
			'unicorn/prefer-set-size': 'error',
			'unicorn/prefer-array-index-of': 'error',
			'unicorn/prefer-blob-reading-methods': 'error',
			'unicorn/prefer-modern-dom-apis': 'error',
			'unicorn/prefer-dom-node-append': 'error',
			'unicorn/prefer-dom-node-remove': 'error',
			'unicorn/prefer-keyboard-event-key': 'error',

			// --- type-aware ---
			// These three supersede the AST-only unicorn `prefer-includes` /
			// `prefer-string-starts-ends-with` / `prefer-array-find`: they catch the
			// same patterns plus `s[0] === x`, `charAt`, `slice`, `indexOf === 0`.
			// `prefer-includes`/`prefer-array-find` are off by omission; the
			// starts/ends one is on via the default correctness category, so disable
			// it explicitly to avoid duplicate diagnostics on the same code.
			'unicorn/prefer-string-starts-ends-with': 'off',
			'typescript/prefer-includes': 'error',
			'typescript/prefer-string-starts-ends-with': 'error',
			'typescript/prefer-find': 'error',
			'typescript/prefer-reduce-type-parameter': 'error',
			'typescript/prefer-return-this-type': 'error',
			'typescript/prefer-as-const': 'error',
			'typescript/no-unnecessary-type-constraint': 'error',

			// Rejected — don't re-add:
			// - `react-perf/jsx-no-new-*`: inline handlers/objects/JSX as props are
			//   idiomatic and only cost when the child is memoized (100+ noisy,
			//   non-autofixable hits).
			// - `unicorn/prefer-at`: `.at()` returns `T | undefined`, breaking
			//   typed-array bitwise code that index access types as `T`.
			// - `typescript/non-nullable-type-assertion-style`: pushes `as` casts
			//   toward `!`, at odds with the deferred `no-non-null-assertion`.
			// - `unicorn/prefer-string-raw`: rewrites one segment of a `+`-built shell
			//   string to a tagged template, tripping `prefer-template`.
			// - `unicorn/no-array-for-each`: autofix isn't type-aware, would break
			//   `Headers`/`Map`/`Set` `.forEach`.
			// - `eslint/no-template-curly-in-string`: our `${…}` literals are
			//   deliberate bash param-expansions in shell bootstrap scripts.
			// - `unicorn/no-negated-condition`: stylistic if/else swaps.
			// - `unicorn/consistent-function-scoping`: debatable, and noisy in tests.
			// - `typescript/no-unnecessary-type-arguments`: churn for no current benefit.

			// --- react hooks correctness (packages/web) ---
			'react-hooks/rules-of-hooks': 'error',
			'react-hooks/exhaustive-deps': 'warn',
			'react/no-unstable-nested-components': 'error',

			// --- imports / architecture ---
			'import/no-cycle': 'error',
			'import/no-duplicates': 'error',
			'import/no-self-import': 'error',
			'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],

			// --- accessibility (jsx-a11y) ---
			// These two ban clickable non-interactive elements
			// (`<div onClick={navigate()}>`), which break cmd/middle-click and
			// keyboard activation. Use `RowLink`/`Button` instead.
			'jsx-a11y/click-events-have-key-events': 'error',
			'jsx-a11y/no-static-element-interactions': 'error',
			'jsx-a11y/no-noninteractive-element-interactions': 'error',
			'jsx-a11y/anchor-is-valid': 'error',
			'jsx-a11y/anchor-has-content': 'error',
			'jsx-a11y/control-has-associated-label': 'error',
			'jsx-a11y/label-has-associated-control': 'error',
			'jsx-a11y/heading-has-content': 'error',
			'jsx-a11y/alt-text': 'error',
			'jsx-a11y/iframe-has-title': 'error',
			'jsx-a11y/autocomplete-valid': 'error',
			'jsx-a11y/aria-props': 'error',
			'jsx-a11y/aria-proptypes': 'error',
			'jsx-a11y/aria-role': 'error',
			'jsx-a11y/aria-unsupported-elements': 'error',
			'jsx-a11y/role-has-required-aria-props': 'error',
			'jsx-a11y/no-aria-hidden-on-focusable': 'error',
			// `autoFocus` on a modal dialog's first field is intentional here, so this
			// rule is off rather than per-dialog overrides.
			'jsx-a11y/no-autofocus': 'off',
		},
		overrides: [
			{
				// Tests and test helpers may use `any`, log freely, and stringify/spread
				// mock objects (URLs, fake records) where these type-aware rules would
				// otherwise false-positive.
				files: ['**/*.test.ts', '**/*.test.tsx', '**/testing/**'],
				rules: {
					'typescript/no-explicit-any': 'off',
					'eslint/no-console': 'off',
					'typescript/no-base-to-string': 'off',
					'typescript/no-misused-spread': 'off',
					// Async functions are routinely passed to `vi.spyOn(...).mockImplementation`
					// for methods (e.g. S3 `send`) whose callback overload types the impl as
					// void-returning, so this rule false-positives on correct async mocks.
					'typescript/no-misused-promises': 'off',
					// Test doubles assert minimal object literals to SDK types on purpose.
					'typescript/consistent-type-assertions': 'off',
					// Redirect-validation tests use `javascript:` URLs as the malicious
					// input they assert is rejected.
					'eslint/no-script-url': 'off',
					// Inline `new Promise((r) => setTimeout(r, ms))` sleeps are fine in
					// tests; the swallowed-rejection footgun the rule guards doesn't apply.
					'eslint/no-promise-executor-return': 'off',
					// Tests concatenate fixture fragments and spread a `Buffer` into an
					// array to compare bytes — both are deliberate.
					'eslint/no-useless-concat': 'off',
					'unicorn/no-useless-spread': 'off',
				},
			},
			{
				// Entrypoints, examples, and dedicated logging modules write to stdout.
				files: ['apps/server/**', 'examples/**', 'scripts/**', '**/log.ts'],
				rules: {
					'eslint/no-console': 'off',
				},
			},
			{
				files: ['packages/core/**', 'packages/api/**'],
				rules: {
					'no-restricted-imports': [
						'error',
						{
							patterns: [
								'@marimo-hub/storage-*',
								'@marimo-hub/compute-*',
								'@marimo-hub/auth-*',
								'@marimo-hub/credentials-*',
								'@marimo-hub/secrets-*',
								'@marimo-hub/notify-*',
							],
						},
					],
				},
			},
		],
	},
	// This `test` block governs ONLY the root-level `vp test` run that
	// `pnpm test:coverage` invokes — it is NOT inherited by the per-package
	// `vp run -r test` (`pnpm test`) runs, which use each package's own config.
	// `packages/web` is excluded here because its `@/` path aliases resolve only
	// under its own vite config; cover it with `pnpm --filter @marimo-hub/web
	// test --coverage`.
	test: {
		exclude: ['**/node_modules/**', '**/dist/**', 'packages/web/**', 'apps/e2e/**'],
		coverage: {
			provider: 'v8',
			reporter: ['text', 'html'],
			exclude: [
				'**/*.test.ts',
				'**/*.test.tsx',
				'**/testing/**',
				'**/dist/**',
				'**/*.config.{ts,js}',
				'**/*.d.ts',
			],
		},
	},
	run: {
		cache: true,
	},
});
