import { build } from 'vite-plus';
import { execFileSync } from 'node:child_process';
import { zipSync, strToU8 } from 'fflate';
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const built = await build({
	configFile: false,
	logLevel: 'silent',
	build: {
		write: false,
		minify: true,
		target: 'es2022',
		lib: { entry: `${root}src/entry.ts`, name: 'MarimoHubBridge', formats: ['iife'] },
	},
});
const output = (Array.isArray(built) ? built[0] : built).output;
const script = output.find((item) => item.type === 'chunk').code;
const launcher = await readFile(`${root}python/launcher.py`, 'utf8');
const extension = await readFile(`${root}python/extension.py`, 'utf8');
const hash = (value) => createHash('sha256').update(value).digest('hex');
const identity = hash(extension + script + launcher);
const version = `0.1.0+${identity.slice(0, 16)}`;
const dist = `marimohub_notebook_bridge-${version}.dist-info`;
const files = {
	'marimohub_notebook_bridge/__init__.py': extension,
	'marimohub_notebook_bridge/bridge.js': script,
	'marimohub_notebook_bridge/identity': identity,
	[`${dist}/METADATA`]: `Metadata-Version: 2.1\nName: marimohub-notebook-bridge\nVersion: ${version}\nRequires-Python: >=3.10\n`,
	[`${dist}/WHEEL`]:
		'Wheel-Version: 1.0\nGenerator: marimohub\nRoot-Is-Purelib: true\nTag: py3-none-any\n',
	[`${dist}/entry_points.txt`]:
		'[marimo.server.asgi.lifespan]\nmarimohub_notebook_bridge = marimohub_notebook_bridge:lifespan\n',
};
const records = Object.entries(files)
	.map(
		([path, value]) =>
			`${path},sha256=${createHash('sha256').update(value).digest('base64url')},${Buffer.byteLength(value)}\n`,
	)
	.join('');
files[`${dist}/RECORD`] = `${records}${dist}/RECORD,,\n`;
const archive = zipSync(
	Object.fromEntries(
		Object.entries(files).map(([path, value]) => [
			path,
			[strToU8(value), { mtime: new Date(2000, 0, 1) }],
		]),
	),
	{ level: 9 },
);
const source = `// Generated by scripts/generate.mjs; do not edit.\nexport const LAUNCHER = ${JSON.stringify(launcher)};\nexport const WHEEL_NAME = 'marimohub_notebook_bridge-${version}-py3-none-any.whl';\nexport const ARTIFACT_ID = '${identity}';\nexport const WHEEL_BASE64 = '${Buffer.from(archive).toString('base64')}';\n`;
const generated = execFileSync(
	'pnpm',
	['exec', 'vp', 'fmt', '--stdin-filepath', 'runtime.generated.ts'],
	{ input: source, encoding: 'utf8' },
);
const target = `${root}src/runtime.generated.ts`;
if (process.argv.includes('--check')) {
	if ((await readFile(target, 'utf8')) !== generated)
		throw new Error(
			'Notebook bridge artifact is stale; run pnpm --filter @marimo-hub/notebook-bridge generate',
		);
} else await writeFile(target, generated);
