/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/v1/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get current user info */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Current user information */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['Me'];
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/version': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get deployment version info */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Deployment version information */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['DeploymentInfo'];
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/capabilities': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get deployment capability flags */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Deployment capability flags */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['Capabilities'];
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List all projects */
		get: {
			parameters: {
				query?: {
					limit?: number;
					cursor?: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of projects with notebook summaries, newest first */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['ProjectPage'];
						};
					};
				};
				/** @description Bad request */
				400: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		/** Create a project */
		post: {
			parameters: {
				query?: never;
				header?: {
					'idempotency-key'?: string;
				};
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						/** @example Data Science */
						name: string;
						/** @example Exploratory analysis notebooks */
						description: string;
						/**
						 * @example [
						 *       "analytics"
						 *     ]
						 */
						tags?: string[];
						federation?: components['schemas']['ProjectFederationInput'];
					};
				};
			};
			responses: {
				/** @description Project created */
				201: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['Project'];
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{pid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get a project */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Project details */
				200: {
					headers: {
						/** @description Strong validator (the resource version). Echo as `If-Match` to guard a write. */
						ETag: string;
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['Project'];
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		/** Delete a project */
		delete: {
			parameters: {
				query?: never;
				header?: {
					'if-match'?: string;
				};
				path: {
					pid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Project deleted */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['SuccessResponse'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Precondition failed (If-Match did not match the current version) */
				412: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		/** Update a project */
		patch: {
			parameters: {
				query?: never;
				header?: {
					'if-match'?: string;
				};
				path: {
					pid: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						/** @example ML Pipeline */
						name?: string;
						description?: string;
						tags?: string[];
						federation?: components['schemas']['ProjectFederationInput'];
					};
				};
			};
			responses: {
				/** @description Project updated */
				200: {
					headers: {
						/** @description Strong validator (the resource version). Echo as `If-Match` to guard a write. */
						ETag: string;
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['Project'];
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Precondition failed (If-Match did not match the current version) */
				412: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		trace?: never;
	};
	'/api/v1/projects/{pid}/members': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List project members */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Project members */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['ProjectMember'][];
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		/** Add a project member */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						/** @example user_01HXY00000000000000000000 */
						user_id: string;
						/**
						 * @example editor
						 * @enum {string}
						 */
						role: 'admin' | 'editor' | 'viewer';
					};
				};
			};
			responses: {
				/** @description Member added */
				201: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['Project'];
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Conflict */
				409: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{pid}/members/{uid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Change a member's role */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					uid: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						/**
						 * @example admin
						 * @enum {string}
						 */
						role: 'admin' | 'editor' | 'viewer';
					};
				};
			};
			responses: {
				/** @description Member role updated */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['Project'];
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Conflict */
				409: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		post?: never;
		/** Remove a project member */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					uid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Member removed */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['SuccessResponse'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Conflict */
				409: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{pid}/events': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List a project's audit events for one day
		 * @description Catalog mutation audit trail (project/notebook lifecycle, membership changes), one UTC day at a time. Admin-only: events may record member management and deletions.
		 */
		get: {
			parameters: {
				query?: {
					/** @description UTC day (defaults to today) */
					date?: string;
				};
				header?: never;
				path: {
					pid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description The day's audit events for this project, in append order */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['AuditEvent'][];
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{pid}/notebooks': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List notebooks in a project */
		get: {
			parameters: {
				query?: {
					limit?: number;
					cursor?: string;
				};
				header?: never;
				path: {
					pid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of notebooks, newest first */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['NotebookPage'];
						};
					};
				};
				/** @description Bad request */
				400: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		/** Create a notebook */
		post: {
			parameters: {
				query?: never;
				header?: {
					'idempotency-key'?: string;
				};
				path: {
					pid: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						/** @example Revenue Analysis */
						title: string;
						/** @example Monthly revenue breakdown */
						description: string;
						/** @example import marimo as mo */
						code: string;
						/**
						 * @example [
						 *       "finance"
						 *     ]
						 */
						tags?: string[];
						readme?: string;
						deps?: string;
						runtime?: {
							python_version?: string;
							marimo_version?: string;
						};
					};
				};
			};
			responses: {
				/** @description Notebook created */
				201: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['NotebookMeta'];
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{pid}/notebooks/git': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create a git-synced workspace notebook */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						/** @example GitHub app */
						title: string;
						/** @example Synced from a git repository */
						description: string;
						/**
						 * @example github
						 * @enum {string}
						 */
						provider?: 'github';
						/** @example marimo-team/marimohub */
						repo: string;
						/** @example main */
						branch: string;
						/** @example apps */
						root_path?: string;
						/** @example my_app.py */
						entry_notebook: string;
						/**
						 * @example [
						 *       "git"
						 *     ]
						 */
						tags?: string[];
						readme?: string;
						runtime?: {
							python_version?: string;
							marimo_version?: string;
						};
					};
				};
			};
			responses: {
				/** @description Git-synced notebook created */
				201: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['GitNotebookCreateResult'];
						};
					};
				};
				/** @description Bad request */
				400: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{pid}/notebooks/{nid}/sync-token/rotate': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Rotate a notebook sync token */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					nid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Sync token rotated */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['SyncToken'];
						};
					};
				};
				/** @description Bad request */
				400: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{pid}/notebooks/{nid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get notebook metadata */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					nid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Notebook detail */
				200: {
					headers: {
						/** @description Strong validator (the resource version). Echo as `If-Match` to guard a write. */
						ETag: string;
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['NotebookDetail'];
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		/** Delete a notebook (soft-delete) */
		delete: {
			parameters: {
				query?: never;
				header?: {
					'if-match'?: string;
				};
				path: {
					pid: string;
					nid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Notebook deleted */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['SuccessResponse'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Precondition failed (If-Match did not match the current version) */
				412: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		/** Update a notebook */
		patch: {
			parameters: {
				query?: never;
				header?: {
					'if-match'?: string;
				};
				path: {
					pid: string;
					nid: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						title?: string;
						description?: string;
						code?: string;
						tags?: string[];
						readme?: string;
						deps?: string;
						/** @example Add regional breakdown */
						message?: string;
					};
				};
			};
			responses: {
				/** @description Notebook updated */
				200: {
					headers: {
						/** @description Strong validator (the resource version). Echo as `If-Match` to guard a write. */
						ETag: string;
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['NotebookMeta'];
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Precondition failed (If-Match did not match the current version) */
				412: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		trace?: never;
	};
	'/api/v1/projects/{pid}/notebooks/{nid}/content': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get notebook code */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					nid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Notebook source code */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: {
								code: string;
							};
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{pid}/notebooks/{nid}/versions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List notebook versions */
		get: {
			parameters: {
				query?: {
					limit?: number;
					cursor?: string;
				};
				header?: never;
				path: {
					pid: string;
					nid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of versions, newest first */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['NotebookVersionPage'];
						};
					};
				};
				/** @description Bad request */
				400: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{pid}/notebooks/{nid}/versions/{vid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get a specific version */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					nid: string;
					vid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Version details with code */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: {
								version: components['schemas']['NotebookVersion'];
								code: string;
							};
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{pid}/notebooks/{nid}/html': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Latest HTML snapshot of the notebook's outputs
		 * @description Serves the newest version's HTML snapshot (captured best-effort at session teardown) raw — the static outputs shown to viewers under MARIMOHUB_VIEWER_MODE=static. `X-Marimohub-Version-Id` / `X-Marimohub-Captured-At` identify the snapshot. 404 with code `NO_HTML_SNAPSHOT` when no version has one.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					nid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description The HTML snapshot, served sandboxed (CSP forces an opaque origin) */
				200: {
					headers: Record<string, unknown>;
					content: {
						'text/html': string;
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{pid}/notebooks/{nid}/versions/{vid}/restore': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Restore a version as a new save */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					nid: string;
					vid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Version restored as a new save; returns the updated notebook */
				201: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['NotebookMeta'];
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{pid}/notebooks/{nid}/duplicate': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Duplicate a notebook */
		post: {
			parameters: {
				query?: never;
				header?: {
					'idempotency-key'?: string;
				};
				path: {
					pid: string;
					nid: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						/** @example Revenue Analysis (copy) */
						title?: string;
					};
				};
			};
			responses: {
				/** @description Notebook duplicated; returns the new notebook */
				201: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['NotebookMeta'];
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{pid}/sessions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List active sessions for a project */
		get: {
			parameters: {
				query?: {
					limit?: number;
					cursor?: string;
				};
				header?: never;
				path: {
					pid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Active sessions for the project, newest first */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['SessionPage'];
						};
					};
				};
				/** @description Bad request */
				400: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{pid}/notebooks/{nid}/sessions/{sid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get a session (status + kernel URL) */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					nid: string;
					sid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Session */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['Session'];
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		/** Terminate a session and destroy sandbox */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					nid: string;
					sid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Session terminated */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['SuccessResponse'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{pid}/notebooks/{nid}/sessions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create a session and provision a sandbox
		 * @description Create-or-reuse: returns the caller’s existing starting/running session for this notebook when one exists, otherwise provisions a new sandbox.
		 */
		post: {
			parameters: {
				query?: never;
				header?: {
					'idempotency-key'?: string;
				};
				path: {
					pid: string;
					nid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Session created or reused */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['SessionCreateResult'];
						};
					};
				};
				/** @description Bad request */
				400: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Resource limit reached */
				429: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{pid}/notebooks/{nid}/sessions/{sid}/heartbeat': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Update session heartbeat */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					nid: string;
					sid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Heartbeat updated */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['Session'];
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{pid}/secrets': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List a project's secrets (metadata only — never a value) */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Secret entries (names, kinds, reference locators) */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['SecretEntry'][];
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{pid}/secrets/{name}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Create or overwrite a project secret (admin only) */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					name: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['SecretInput'];
				};
			};
			responses: {
				/** @description Secret created or overwritten */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['SecretEntry'];
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		post?: never;
		/** Delete a project secret (admin only) */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					name: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Secret deleted */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['SuccessResponse'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{pid}/secrets/validate': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Test that a reference resolves, without saving it (admin only)
		 * @description Dry-run: attempts to resolve the reference so a broken locator surfaces before it fails a session closed. Never returns the value — only ok/reason.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['SecretInput'];
				};
			};
			responses: {
				/** @description Whether the input resolves */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['SecretValidateResult'];
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Not found */
				404: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Service unavailable */
				503: {
					headers: {
						/** @description Seconds to wait before retrying. */
						'Retry-After': string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/users': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Resolve user ids to display identities
		 * @description Batch-resolve opaque user ids (the auth `sub` stored as a notebook `author` or session `user_id`) into `{ id, email, name }`. Ids with no recorded identity are omitted from the result map.
		 */
		get: {
			parameters: {
				query?: {
					/** @description Comma-separated user ids. */
					ids?: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Map of user id → resolved identity (unknown ids omitted) */
				200: {
					headers: Record<string, unknown>;
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: Record<string, components['schemas']['User']>;
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: Record<string, unknown>;
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		Me: {
			id: string;
			email: string;
			logout_url: string | null;
		};
		ErrorResponse: {
			/** @enum {boolean} */
			success: false;
			error: {
				/** @enum {string} */
				code:
					| 'BAD_REQUEST'
					| 'UNAUTHORIZED'
					| 'FORBIDDEN'
					| 'NOT_FOUND'
					| 'CONFLICT'
					| 'GONE'
					| 'PRECONDITION_FAILED'
					| 'PAYLOAD_TOO_LARGE'
					| 'VALIDATION_ERROR'
					| 'RESOURCE_EXHAUSTED'
					| 'NOT_INITIALIZED'
					| 'SERVICE_UNAVAILABLE'
					| 'INTERNAL_ERROR';
				message: string;
				request_id?: string;
			};
		};
		DeploymentInfo: {
			version: string;
			image: string | null;
			sandbox_image: string | null;
			started_at: string | null;
			replica: string | null;
			node: string | null;
			backends: {
				storage: string;
				compute: string;
				auth: string;
			};
		};
		Capabilities: {
			federation: {
				available: boolean;
			};
			/** @enum {string} */
			viewer_mode: 'static' | 'ephemeral-sandbox';
			limits: {
				max_concurrent_sessions_per_user: number | null;
				max_request_bytes: number;
				max_versions_per_notebook: number;
				default_page_size: number;
				max_page_size: number;
			};
		};
		ProjectPage: {
			items: components['schemas']['SnapshotProjectEntry'][];
			next_cursor: string | null;
		};
		SnapshotProjectEntry: {
			id: string;
			name: string;
			description: string;
			owner: string;
			/** @enum {string} */
			status: 'active' | 'deleted';
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			created_at: string;
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			updated_at: string;
			notebook_count: number;
		};
		Project: {
			id: string;
			name: string;
			description: string;
			owner: string;
			members: components['schemas']['ProjectMember'][];
			/** @enum {string} */
			status: 'active' | 'deleted';
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			created_at: string;
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			updated_at: string;
			tags: string[];
			federation?: components['schemas']['ProjectFederation'];
			/** @enum {string|null} */
			your_role: 'admin' | 'editor' | 'viewer' | null;
		};
		ProjectMember: {
			user_id: string;
			/** @enum {string} */
			role: 'admin' | 'editor' | 'viewer';
		};
		ProjectFederation: {
			enabled: boolean;
			target?: string;
		};
		ProjectFederationInput: {
			/** @example true */
			enabled: boolean;
			/** @example default */
			target?: string;
		};
		SuccessResponse: {
			/** @enum {boolean} */
			success: true;
		};
		AuditEvent: {
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			ts: string;
			/** @example project.update */
			event: string;
			actor: string;
		} & Record<string, unknown>;
		NotebookPage: {
			items: components['schemas']['SnapshotNotebookEntry'][];
			next_cursor: string | null;
		};
		SnapshotNotebookEntry: {
			id: string;
			title: string;
			description: string;
			/** @enum {string} */
			status: 'draft' | 'active' | 'archived' | 'deleted';
			/** @enum {string} */
			source_type: 'local' | 'git';
			author: string;
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			created_at: string;
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			updated_at: string;
			tags: string[];
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			last_run_at: string | null;
		};
		NotebookMeta: {
			id: string;
			project_id: string;
			title: string;
			description: string;
			/** @enum {string} */
			status: 'draft' | 'active' | 'archived' | 'deleted';
			author: string;
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			created_at: string;
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			updated_at: string;
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			last_run_at: string | null;
			tags: string[];
			runtime?: {
				python_version?: string;
				marimo_version?: string;
			};
		};
		GitNotebookCreateResult: {
			notebook: components['schemas']['NotebookMeta'];
			sync_url: string;
			sync_token: string;
		};
		SyncToken: {
			sync_url: string;
			sync_token: string;
		};
		NotebookDetail: {
			meta: components['schemas']['NotebookMeta'];
			readme: string | null;
			source: components['schemas']['Source'];
		};
		Source:
			| {
					/** @enum {string} */
					type: 'local';
					current_version_id: string;
			  }
			| {
					/** @enum {string} */
					type: 'git';
					/** @enum {string} */
					provider: 'github';
					repo: string;
					branch: string;
					root_path: string;
					entry_notebook: string;
					/** @enum {string} */
					sync_mode: 'push';
					current_version_id: string | null;
					commit: string | null;
					/**
					 * Format: date-time
					 * @example 2025-03-05T14:00:00Z
					 */
					last_synced_at: string | null;
			  };
		NotebookVersionPage: {
			items: components['schemas']['NotebookVersion'][];
			next_cursor: string | null;
		};
		NotebookVersion: {
			version_id: string;
			notebook_id: string;
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			saved_at: string;
			author: string;
			message: string;
			parent_id: string | null;
			html_snapshot?: components['schemas']['SnapshotDescriptor'];
			session_snapshot?: components['schemas']['SnapshotDescriptor'];
		};
		SnapshotDescriptor: {
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			captured_at: string;
			size_bytes: number;
		};
		SessionPage: {
			items: components['schemas']['Session'][];
			next_cursor: string | null;
		};
		Session: {
			session_id: string;
			notebook_id: string;
			project_id: string;
			user_id: string;
			/** @enum {string} */
			status: 'starting' | 'running' | 'terminating' | 'terminated' | 'failed' | 'expired';
			sandbox_url?: string;
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			started_at: string;
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			last_heartbeat: string;
			ephemeral?: boolean;
			error?: {
				code: string;
				message: string;
			};
		};
		SessionCreateResult: components['schemas']['Session'] & {
			reused: boolean;
		};
		SecretEntry: {
			name: string;
			/** @enum {string} */
			kind: 'managed' | 'reference';
			ref?: {
				/** @example aws-sm */
				backend: string;
				/** @example prod/ai#OPENAI_API_KEY */
				locator: string;
				/** @enum {string} */
				expand?: 'json';
				prefix?: string;
			};
			created_by: string;
			created_at: string;
			updated_at: string;
		};
		SecretInput:
			| {
					/** @enum {string} */
					kind: 'managed';
					value: string;
			  }
			| {
					/** @enum {string} */
					kind: 'reference';
					/** @example aws-sm */
					backend: string;
					/** @example prod/ai#OPENAI_API_KEY */
					locator: string;
					/** @enum {string} */
					expand?: 'json';
					prefix?: string;
			  };
		SecretValidateResult: {
			ok: boolean;
			reason?: string;
		};
		User: {
			id: string;
			email: string;
			name: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
