import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
import { describe, expect, it } from 'vitest';

const SPEC_URL = new URL('../../api/openapi.yaml', import.meta.url);
const SCHEMA_PATH = fileURLToPath(new URL('./schema.ts', import.meta.url));
const GENERATED_HEADER =
	/^\/\*\*\n \* This file was auto-generated by openapi-typescript\.\n \* Do not make direct changes to the file\.\n \*\/\n*/;

function normalize(source: string): string {
	return source
		.replace(GENERATED_HEADER, '')
		.replaceAll(/["']/g, '"')
		.replaceAll(/,\s*([}\])])/g, '$1')
		.replaceAll(/([:(=])\s*\|/g, '$1')
		.replaceAll(/\s+/g, '');
}

describe('client schema drift', () => {
	it('src/schema.ts is in sync with packages/api/openapi.yaml (run `pnpm --filter @marimo-hub/client generate` to update)', async () => {
		const generated = astToString(await openapiTS(SPEC_URL));

		if (process.env.UPDATE_CLIENT_SCHEMA) {
			writeFileSync(
				SCHEMA_PATH,
				`/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n\n${generated}`,
			);
		}

		const committed = normalize(readFileSync(SCHEMA_PATH, 'utf8'));
		const expected = normalize(generated);
		if (committed !== expected) {
			let index = 0;
			while (committed[index] === expected[index]) index++;
			expect(committed.slice(index, index + 120)).toBe(expected.slice(index, index + 120));
		}
		expect(committed.length).toBe(expected.length);
	});
});
