/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get current user info */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Current user information */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: {
								id: string;
								email: string;
								logoutUrl: string | null;
							};
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/projects': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List all projects */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of projects with notebook summaries */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['SnapshotProjectEntry'][];
						};
					};
				};
			};
		};
		put?: never;
		/** Create a project */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						/** @example Data Science */
						name: string;
						/** @example Exploratory analysis notebooks */
						description: string;
						/**
						 * @example [
						 *       "analytics"
						 *     ]
						 */
						tags?: string[];
					};
				};
			};
			responses: {
				/** @description Project created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['Project'];
						};
					};
				};
				/** @description Validation error */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/projects/{pid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get a project */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Project details */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['Project'];
						};
					};
				};
				/** @description Project not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		/** Update a project */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						/** @example ML Pipeline */
						name?: string;
						description?: string;
						tags?: string[];
					};
				};
			};
			responses: {
				/** @description Project updated */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['Project'];
						};
					};
				};
				/** @description Insufficient role */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Project not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		post?: never;
		/** Delete a project */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Project deleted */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['SuccessResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Project not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/projects/{pid}/notebooks': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List notebooks in a project */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of notebooks */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['SnapshotNotebookEntry'][];
						};
					};
				};
				/** @description Project not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		/** Create a notebook */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						/** @example Revenue Analysis */
						title: string;
						/** @example Monthly revenue breakdown */
						description: string;
						/** @example import marimo as mo */
						code: string;
						/**
						 * @example [
						 *       "finance"
						 *     ]
						 */
						tags?: string[];
						readme?: string;
						deps?: string;
						runtime?: {
							python_version?: string;
							marimo_version?: string;
						};
					};
				};
			};
			responses: {
				/** @description Notebook created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['NotebookMeta'];
						};
					};
				};
				/** @description Insufficient role */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Project not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/projects/{pid}/notebooks/{nid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get notebook metadata */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					nid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Notebook detail */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['NotebookDetail'];
						};
					};
				};
				/** @description Notebook not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		/** Update a notebook */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					nid: string;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': {
						title?: string;
						description?: string;
						code?: string;
						tags?: string[];
						readme?: string;
						deps?: string;
						/** @example Add regional breakdown */
						message?: string;
					};
				};
			};
			responses: {
				/** @description Notebook updated */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['NotebookMeta'];
						};
					};
				};
				/** @description Insufficient role */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Notebook not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		post?: never;
		/** Delete a notebook (soft-delete) */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					nid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Notebook deleted */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['SuccessResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Notebook not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/projects/{pid}/notebooks/{nid}/content': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get notebook code */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					nid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Notebook source code */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: {
								code: string;
							};
						};
					};
				};
				/** @description Notebook not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/projects/{pid}/notebooks/{nid}/versions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List notebook versions */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					nid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of versions */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['Version'][];
						};
					};
				};
				/** @description Notebook not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/projects/{pid}/notebooks/{nid}/versions/{vid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get a specific version */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					nid: string;
					vid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Version details with code */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: {
								version: components['schemas']['Version'];
								code: string;
							};
						};
					};
				};
				/** @description Version not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/projects/{pid}/notebooks/{nid}/sessions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create a session and provision a sandbox */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					nid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Session created */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['Session'];
						};
					};
				};
				/** @description Insufficient role */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Notebook not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Validation error */
				422: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Concurrent session limit reached */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/projects/{pid}/notebooks/{nid}/sessions/{sid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Terminate a session and destroy sandbox */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					nid: string;
					sid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Session terminated */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['SuccessResponse'];
					};
				};
				/** @description Insufficient role */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Session not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/projects/{pid}/notebooks/{nid}/sessions/{sid}/heartbeat': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Update session heartbeat */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					pid: string;
					nid: string;
					sid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Heartbeat updated */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {boolean} */
							success: true;
							data: components['schemas']['Session'];
						};
					};
				};
				/** @description Insufficient role */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Session not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		SnapshotProjectEntry: {
			id: string;
			name: string;
			description: string;
			owner: string;
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			created_at: string;
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			updated_at: string;
			notebook_count: number;
			notebooks: components['schemas']['SnapshotNotebookEntry'][];
		};
		SnapshotNotebookEntry: {
			id: string;
			title: string;
			description: string;
			/** @enum {string} */
			status: 'draft' | 'active' | 'archived' | 'deleted';
			/** @enum {string} */
			source_type: 'local' | 'github';
			author: string;
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			created_at: string;
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			updated_at: string;
			tags: string[];
			last_run_at: string | null;
		};
		Project: {
			/** @enum {number} */
			schema_version: 1;
			id: string;
			name: string;
			description: string;
			owner: string;
			members: components['schemas']['ProjectMember'][];
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			created_at: string;
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			updated_at: string;
			tags: string[];
		};
		ProjectMember: {
			user_id: string;
			/** @enum {string} */
			role: 'admin' | 'editor' | 'viewer';
		};
		ErrorResponse: {
			/** @enum {boolean} */
			success: false;
			error: {
				code: string;
				message: string;
			};
		};
		SuccessResponse: {
			/** @enum {boolean} */
			success: true;
		};
		NotebookMeta: {
			/** @enum {number} */
			schema_version: 1;
			id: string;
			project_id: string;
			title: string;
			description: string;
			/** @enum {string} */
			status: 'draft' | 'active' | 'archived' | 'deleted';
			author: string;
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			created_at: string;
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			updated_at: string;
			last_run_at: string | null;
			tags: string[];
			runtime?: {
				python_version?: string;
				marimo_version?: string;
			};
		};
		NotebookDetail: {
			meta: components['schemas']['NotebookMeta'];
			readme: string | null;
			source: components['schemas']['Source'];
		};
		Source:
			| {
					/** @enum {number} */
					schema_version: 1;
					/** @enum {string} */
					type: 'local';
					current_version_id: string;
			  }
			| {
					/** @enum {number} */
					schema_version: 1;
					/** @enum {string} */
					type: 'github';
					repo: string;
					branch: string;
					path: string;
					commit: string;
					/**
					 * Format: date-time
					 * @example 2025-03-05T14:00:00Z
					 */
					last_synced_at: string;
			  };
		Version: {
			/** @enum {number} */
			schema_version: 1;
			version_id: string;
			notebook_id: string;
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			saved_at: string;
			author: string;
			message: string;
			parent_id: string | null;
		};
		Session: {
			session_id: string;
			notebook_id: string;
			project_id: string;
			/** @enum {string} */
			status: 'starting' | 'running' | 'idle' | 'terminated' | 'expired';
			sandbox_url?: string;
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			started_at: string;
			/**
			 * Format: date-time
			 * @example 2025-03-05T14:00:00Z
			 */
			last_heartbeat: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
