/**
 * Renders the config registry (`spec.ts`) into the operator-facing
 * `docs/configuration.md`. Pure and deterministic: same input → byte-identical
 * output, so the doc-sync test can assert the committed file matches.
 */
import type { ConfigGroup, ConfigVar } from './spec';

const AUTOGEN_HEADER = `<!--
  AUTOGENERATED — do not edit by hand.
  Source of truth: packages/config/src/spec.ts
  Regenerate:      pnpm --filter @marimo-hub/config docs:generate
-->`;

/** Escape a value for use inside a Markdown table cell. */
function cell(value: string): string {
	return value.replaceAll('|', '\\|').replaceAll('\n', ' ');
}

/** Wrap in backticks, or render an em-dash when absent. */
function code(value: string | undefined): string {
	return value ? `\`${value}\`` : '—';
}

function renderVarsTable(vars: ConfigVar[]): string {
	const rows = vars.map((v) => {
		const name = v.secret ? `\`${v.id}\` 🔒` : `\`${v.id}\``;
		return `| ${name} | ${cell(v.description)} | ${v.required ? 'Yes' : '—'} | ${code(
			v.default,
		)} | ${code(v.example)} |`;
	});
	return [
		'| Variable | Description | Required | Default | Example |',
		'| --- | --- | --- | --- | --- |',
		...rows,
	].join('\n');
}

function renderGroup(group: ConfigGroup): string {
	const parts: string[] = [`## ${group.name}`, ''];

	if (group.selector) {
		const values = group.backends
			.map((b) => b.selectorValue)
			.filter((v): v is string => Boolean(v))
			.map((v) => `\`${v}\``)
			.join(', ');
		const def = group.selectorDefault ? ` (default \`${group.selectorDefault}\`)` : '';
		parts.push(`Selected by \`${group.selector}\`${def}; one of ${values}.`, '');
	}

	if (group.description) parts.push(group.description, '');

	for (const backend of group.backends) {
		parts.push(`### ${backend.name}`, '');
		if (backend.selectorValue && group.selector) {
			parts.push(`\`${group.selector}=${backend.selectorValue}\``, '');
		}
		if (backend.description) parts.push(backend.description, '');
		if (backend.vars.length > 0) {
			parts.push(renderVarsTable(backend.vars), '');
		} else {
			parts.push('_No environment variables to set here._', '');
		}
	}

	return parts.join('\n');
}

export function renderConfigDocs(spec: ConfigGroup[]): string {
	const body = [
		'---',
		'description: Authoritative generated reference for every marimohub configuration variable and backend selector.',
		'---',
		'',
		AUTOGEN_HEADER,
		'',
		'# Configuration reference',
		'',
		'Every marimohub configuration variable, grouped by category and backend. ' +
			'Each category has a `*_BACKEND` selector that chooses an adapter; only that ' +
			"backend's variables are read.",
		'',
		'🔒 marks a sensitive value (a secret).',
		'',
		...spec.map(renderGroup),
	].join('\n');

	// Single trailing newline (the formatter expects exactly one).
	return `${body.replace(/\n+$/, '')}\n`;
}
