secretResolvers:
  kubernetes:
    enabled: true
    cacheTtlSeconds: 0
    allowedSecrets:
      - namespace: connections-a
        name: provider-a
        projects: '*'
      - namespace: connections-a
        name: provider-b
        projects: [proj-0000000000000000]
      - namespace: connections-b
        name: provider-c
        projects: '*'
