apiVersion: v1
kind: Service
metadata:
  name: marimohub
  labels: { app: marimohub }
spec:
  type: ClusterIP
  selector: { app: marimohub }
  ports:
    - name: http
      port: 80
      targetPort: 3000
