{{- if and (not .Values.secrets.existingSecret) .Values.secrets.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "marimohub.fullname" . }}-secrets
  labels:
    {{- include "marimohub.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
