import { createRoute, z } from '@hono/zod-openapi';
import type { Context } from 'hono';
import {
	BadRequestError,
	createSlidingWindowBudget,
	joinUrlPath,
	parseCliAuthorizationCode,
	ResourceExhaustedError,
	TokenGrantSchema,
} from '@marimo-hub/core';
import type { SlidingWindowBudget } from '@marimo-hub/core';
import { auditTokenCreation } from '../tokenAudit';
import {
	assertSessionAuthenticated,
	assertTokenGrantProjectsVisible,
	commonErrors,
	createApp,
	errorResponses,
	jsonBody,
	jsonContent,
	resolvePublicBaseUrl,
	SESSION_ONLY_SECURITY,
} from '../shared';
import type { HonoEnv } from '../shared';

const CallbackUriSchema = z.url().max(300).openapi({
	description:
		'HTTP loopback callback using 127.0.0.1 or [::1], an explicit port, and the exact /callback path.',
	example: 'http://127.0.0.1:49152/callback',
});
const StateSchema = z
	.string()
	.regex(/^[A-Za-z0-9_-]{32,128}$/)
	.openapi({ description: 'Opaque base64url CSRF state generated by the CLI.' });
const CodeChallengeSchema = z
	.string()
	.regex(/^[A-Za-z0-9_-]{43}$/)
	.openapi({ description: 'Base64url-encoded SHA-256 PKCE challenge generated by the CLI.' });
const CodeVerifierSchema = z.string().regex(/^[A-Za-z0-9_-]{43,128}$/);
const AuthorizationCodeSchema = z.string().min(1).max(100);
const TokenNameSchema = z
	.string()
	.trim()
	.min(1)
	.max(100)
	.openapi({ description: "Name shown in the user's personal access token list." });
const TokenLifetimeSchema = z
	.number()
	.int()
	.min(1)
	.max(3650)
	.openapi({ description: 'Lifetime of the personal access token minted during exchange.' });

const ApproveBodySchema = z.strictObject({
	callback_uri: CallbackUriSchema,
	state: StateSchema,
	code_challenge: CodeChallengeSchema,
	token_name: TokenNameSchema,
	expires_in_days: TokenLifetimeSchema,
});

const ScopedApproveBodySchema = ApproveBodySchema.extend({
	requested_grant: TokenGrantSchema,
	grant: TokenGrantSchema,
});

const ExchangeBodySchema = z.strictObject({
	code: AuthorizationCodeSchema,
	code_verifier: CodeVerifierSchema,
});

const DeviceAuthorizationBodySchema = z.strictObject({
	code_challenge: CodeChallengeSchema,
});

const ScopedDeviceAuthorizationBodySchema = DeviceAuthorizationBodySchema.extend({
	grant: TokenGrantSchema,
});

const DeviceApprovalBodySchema = z.strictObject({
	user_code: z.string().trim().min(8).max(20),
	token_name: TokenNameSchema,
	expires_in_days: TokenLifetimeSchema,
});

const ScopedDeviceApprovalBodySchema = DeviceApprovalBodySchema.extend({
	grant: TokenGrantSchema,
});

const DevicePollBodySchema = z.strictObject({
	device_code: AuthorizationCodeSchema,
	code_verifier: CodeVerifierSchema,
});

const AUTHORIZATION_EXCHANGE_LIMIT = 5;
const GLOBAL_EXCHANGE_LIMIT = 600;
const EXCHANGE_WINDOW_MS = 60_000;
const authorizationExchangeBudget = createSlidingWindowBudget<string>({
	limit: AUTHORIZATION_EXCHANGE_LIMIT,
	windowMs: EXCHANGE_WINDOW_MS,
});
const globalExchangeBudget = createSlidingWindowBudget<'deployment'>({
	limit: GLOBAL_EXCHANGE_LIMIT,
	windowMs: EXCHANGE_WINDOW_MS,
});
const DEVICE_REQUEST_LIMIT = 30;
const DEVICE_POLL_LIMIT = 15;
const GLOBAL_DEVICE_POLL_LIMIT = 6_000;
const USER_CODE_ATTEMPT_LIMIT = 5;
const DEVICE_REQUEST_WINDOW_MS = 60_000;
const USER_CODE_ATTEMPT_WINDOW_MS = 10 * 60_000;
const deviceRequestBudget = createSlidingWindowBudget<'deployment'>({
	limit: DEVICE_REQUEST_LIMIT,
	windowMs: DEVICE_REQUEST_WINDOW_MS,
});
const devicePollBudget = createSlidingWindowBudget<string>({
	limit: DEVICE_POLL_LIMIT,
	windowMs: EXCHANGE_WINDOW_MS,
});
const globalDevicePollBudget = createSlidingWindowBudget<'deployment'>({
	limit: GLOBAL_DEVICE_POLL_LIMIT,
	windowMs: EXCHANGE_WINDOW_MS,
});
const userCodeAttemptBudget = createSlidingWindowBudget<string>({
	limit: USER_CODE_ATTEMPT_LIMIT,
	windowMs: USER_CODE_ATTEMPT_WINDOW_MS,
});
const userCodePreviewBudget = createSlidingWindowBudget<string>({
	limit: USER_CODE_ATTEMPT_LIMIT,
	windowMs: USER_CODE_ATTEMPT_WINDOW_MS,
});

function consumeBudget<Key>(budget: SlidingWindowBudget<Key>, key: Key, message: string): void {
	if (!budget.consume(key)) throw new ResourceExhaustedError(message);
}

function preventCaching(c: { header(name: string, value: string): void }): void {
	c.header('Cache-Control', 'no-store');
	c.header('Pragma', 'no-cache');
}

function assertExchangeAllowed(code: string): void {
	const authorization = parseCliAuthorizationCode(code);
	if (authorization === null) return;
	consumeBudget(
		globalExchangeBudget,
		'deployment',
		'Too many CLI token exchanges; try again later.',
	);
	consumeBudget(
		authorizationExchangeBudget,
		authorization.id,
		'Too many attempts for this CLI authorization code.',
	);
}

function assertDeviceRequestAllowed(): void {
	consumeBudget(
		deviceRequestBudget,
		'deployment',
		'Too many CLI device authorization requests; try again later.',
	);
}

function assertDevicePollAllowed(code: string): void {
	consumeBudget(
		globalDevicePollBudget,
		'deployment',
		'Too many CLI device authorization polls; try again later.',
	);
	const authorization = parseCliAuthorizationCode(code);
	if (authorization === null) return;
	consumeBudget(
		devicePollBudget,
		authorization.id,
		'CLI device authorization is being polled too frequently.',
	);
}

function assertUserCodeAttemptAllowed(userId: string): void {
	consumeBudget(
		userCodeAttemptBudget,
		userId,
		'Too many CLI device code attempts; try again later.',
	);
}

function assertUserCodePreviewAllowed(userId: string): void {
	consumeBudget(
		userCodePreviewBudget,
		userId,
		'Too many CLI device code previews; try again later.',
	);
}

function loopbackCallback(raw: string): URL {
	const url = new URL(raw);
	const loopback = url.hostname === '127.0.0.1' || url.hostname === '[::1]';
	if (
		url.protocol !== 'http:' ||
		!loopback ||
		!url.port ||
		url.username ||
		url.password ||
		url.pathname !== '/callback' ||
		url.search ||
		url.hash
	) {
		throw new BadRequestError('callback_uri must be an HTTP loopback URL ending in /callback');
	}
	return url;
}

function loopbackApprovalData(
	callback: URL,
	state: string,
	approved: { code: string; expiresAt: string },
) {
	callback.searchParams.set('code', approved.code);
	callback.searchParams.set('state', state);
	return { redirect_uri: callback.toString(), expires_at: approved.expiresAt };
}

function deviceAuthorizationData(
	c: Context<HonoEnv>,
	requested: { code: string; userCode: string },
) {
	const publicBaseUrl = resolvePublicBaseUrl(c, c.get('deps').sandbox.appBaseUrl);
	const verification = new URL(joinUrlPath(publicBaseUrl, '/cli/device'));
	const complete = new URL(verification);
	complete.searchParams.set('user_code', requested.userCode);
	return {
		device_code: requested.code,
		user_code: requested.userCode,
		verification_uri: verification.toString(),
		verification_uri_complete: complete.toString(),
		expires_in: 10 * 60,
		interval: 5,
	};
}

const approveAuthorization = createRoute({
	method: 'post',
	path: '/me/cli-authorizations',
	operationId: 'auth.cli.approve',
	'x-cli-hidden': true,
	tags: ['Auth'],
	summary: 'Approve a CLI login',
	description:
		'Creates a one-time code that is bound to the CLI PKCE challenge. ' +
		'Requires a browser session. Exchange creates the personal access token.',
	security: SESSION_ONLY_SECURITY,
	request: { body: jsonBody(ApproveBodySchema) },
	responses: {
		201: jsonContent(
			z.object({
				success: z.literal(true),
				data: z.object({
					redirect_uri: z.url(),
					expires_at: z.string().openapi({ format: 'date-time' }),
				}),
			}),
			'Loopback callback carrying the one-time authorization code',
		),
		...commonErrors(),
		...errorResponses(400, 403, 429),
	},
});

const approveScopedAuthorization = createRoute({
	method: 'post',
	path: '/me/cli-authorizations/scoped',
	operationId: 'auth.cli.approveScoped',
	'x-cli-hidden': true,
	tags: ['Auth'],
	summary: 'Approve a scoped CLI login',
	security: SESSION_ONLY_SECURITY,
	request: { body: jsonBody(ScopedApproveBodySchema) },
	responses: {
		201: jsonContent(
			z.object({
				success: z.literal(true),
				data: z.object({
					redirect_uri: z.url(),
					expires_at: z.string().openapi({ format: 'date-time' }),
				}),
			}),
			'Loopback callback carrying the one-time authorization code',
		),
		...commonErrors(),
		...errorResponses(400, 403, 404, 429),
	},
});

const exchangeAuthorization = createRoute({
	method: 'post',
	path: '/token',
	operationId: 'auth.cli.exchange',
	'x-cli-hidden': true,
	tags: ['Auth'],
	summary: 'Exchange a CLI authorization code',
	description:
		'Public PKCE exchange for loopback login. The code is short-lived and single-use. ' +
		'Exchange also requires the verifier held by the CLI.',
	security: [],
	request: { body: jsonBody(ExchangeBodySchema) },
	responses: {
		200: jsonContent(
			z.object({
				success: z.literal(true),
				data: z.object({ token: z.string() }),
			}),
			'The new personal access token',
		),
		...errorResponses(400, 413, 422, 429, 500, 503),
	},
});

const approveDeviceAuthorization = createRoute({
	method: 'post',
	path: '/me/cli-device-authorizations',
	operationId: 'auth.cli.device.approve',
	'x-cli-hidden': true,
	tags: ['Auth'],
	summary: 'Approve a CLI device login',
	description:
		'Approves a short-lived device code for the signed-in user. ' +
		'Requires a browser session. Personal access tokens cannot approve device logins.',
	security: SESSION_ONLY_SECURITY,
	request: { body: jsonBody(DeviceApprovalBodySchema) },
	responses: {
		200: jsonContent(
			z.object({
				success: z.literal(true),
				data: z.object({ expires_at: z.string().openapi({ format: 'date-time' }) }),
			}),
			'Device authorization approved',
		),
		...commonErrors(),
		...errorResponses(400, 403, 429),
	},
});

const previewDeviceAuthorization = createRoute({
	method: 'get',
	path: '/me/cli-device-authorizations/{userCode}',
	operationId: 'auth.cli.device.preview',
	'x-cli-hidden': true,
	tags: ['Auth'],
	summary: 'Preview a CLI device login',
	security: SESSION_ONLY_SECURITY,
	request: {
		params: z.object({
			userCode: z
				.string()
				.trim()
				.min(8)
				.max(20)
				.openapi({ param: { name: 'userCode', in: 'path' } }),
		}),
	},
	responses: {
		200: jsonContent(
			z.object({
				success: z.literal(true),
				data: z.discriminatedUnion('status', [
					z.object({
						status: z.literal('legacy'),
						expires_at: z.string().openapi({ format: 'date-time' }),
					}),
					z.object({
						status: z.literal('scoped'),
						requested_grant: TokenGrantSchema,
						expires_at: z.string().openapi({ format: 'date-time' }),
					}),
				]),
			}),
			'CLI device authorization type and requested grant',
		),
		...commonErrors(),
		...errorResponses(400, 403, 404, 429),
	},
});

const approveScopedDeviceAuthorization = createRoute({
	method: 'post',
	path: '/me/cli-device-authorizations/scoped',
	operationId: 'auth.cli.device.approveScoped',
	'x-cli-hidden': true,
	tags: ['Auth'],
	summary: 'Approve a scoped CLI device login',
	security: SESSION_ONLY_SECURITY,
	request: { body: jsonBody(ScopedDeviceApprovalBodySchema) },
	responses: {
		200: jsonContent(
			z.object({
				success: z.literal(true),
				data: z.object({ expires_at: z.string().openapi({ format: 'date-time' }) }),
			}),
			'Device authorization approved',
		),
		...commonErrors(),
		...errorResponses(400, 403, 404, 429),
	},
});

const requestDeviceAuthorization = createRoute({
	method: 'post',
	path: '/device-authorizations',
	operationId: 'auth.cli.device.request',
	'x-cli-hidden': true,
	tags: ['Auth'],
	summary: 'Start a CLI device login',
	description:
		'Returns a high-entropy device code that is bound to the PKCE challenge. ' +
		'Also returns a short code for browser approval.',
	security: [],
	request: { body: jsonBody(DeviceAuthorizationBodySchema) },
	responses: {
		200: jsonContent(
			z.object({
				success: z.literal(true),
				data: z.object({
					device_code: z.string(),
					user_code: z.string(),
					verification_uri: z.url(),
					verification_uri_complete: z.url(),
					expires_in: z.number().int(),
					interval: z.number().int(),
				}),
			}),
			'Device and user verification codes',
		),
		...errorResponses(413, 422, 429, 500, 503),
	},
});

const requestScopedDeviceAuthorization = createRoute({
	method: 'post',
	path: '/device-authorizations/scoped',
	operationId: 'auth.cli.device.requestScoped',
	'x-cli-hidden': true,
	tags: ['Auth'],
	summary: 'Start a scoped CLI device login',
	security: [],
	request: { body: jsonBody(ScopedDeviceAuthorizationBodySchema) },
	responses: requestDeviceAuthorization.responses,
});

const pollDeviceAuthorization = createRoute({
	method: 'post',
	path: '/device-token',
	operationId: 'auth.cli.device.poll',
	'x-cli-hidden': true,
	tags: ['Auth'],
	summary: 'Poll a CLI device login',
	description:
		'Returns 202 while browser approval is pending. ' +
		'Returns a new personal access token once after approval.',
	security: [],
	request: { body: jsonBody(DevicePollBodySchema) },
	responses: {
		200: jsonContent(
			z.object({ success: z.literal(true), data: z.object({ token: z.string() }) }),
			'The new personal access token',
		),
		202: jsonContent(
			z.object({
				success: z.literal(true),
				data: z.object({ status: z.literal('authorization_pending') }),
			}),
			'Browser approval is still pending',
		),
		...errorResponses(400, 413, 422, 429, 500, 503),
	},
});

const app = createApp();

app.openapi(approveAuthorization, async (c) => {
	assertSessionAuthenticated(c, 'approve CLI logins');
	const body = c.req.valid('json');
	const callback = loopbackCallback(body.callback_uri);
	const approved = await c.get('deps').services.cliAuthorizations.approve(
		{
			codeChallenge: body.code_challenge,
			tokenName: body.token_name,
			expiresInDays: body.expires_in_days,
		},
		c.get('user').id,
	);
	preventCaching(c);
	return c.json(
		{
			success: true as const,
			data: loopbackApprovalData(callback, body.state, approved),
		},
		201,
	);
});

app.openapi(approveScopedAuthorization, async (c) => {
	assertSessionAuthenticated(c, 'approve CLI logins');
	const deps = c.get('deps');
	const user = c.get('user');
	const body = c.req.valid('json');
	const callback = loopbackCallback(body.callback_uri);
	await assertTokenGrantProjectsVisible(deps, user, body.grant);
	const approved = await deps.services.cliAuthorizations.approveScoped(
		{
			codeChallenge: body.code_challenge,
			tokenName: body.token_name,
			expiresInDays: body.expires_in_days,
			requestedGrant: body.requested_grant,
			grant: body.grant,
		},
		user.id,
	);
	preventCaching(c);
	return c.json(
		{
			success: true as const,
			data: loopbackApprovalData(callback, body.state, approved),
		},
		201,
	);
});

app.openapi(approveDeviceAuthorization, async (c) => {
	assertSessionAuthenticated(c, 'approve CLI device logins');
	const userId = c.get('user').id;
	assertUserCodeAttemptAllowed(userId);
	const body = c.req.valid('json');
	const approved = await c
		.get('deps')
		.services.cliAuthorizations.approveDevice(
			body.user_code,
			{ tokenName: body.token_name, expiresInDays: body.expires_in_days },
			userId,
		);
	preventCaching(c);
	return c.json({ success: true as const, data: { expires_at: approved.expiresAt } }, 200);
});

app.openapi(previewDeviceAuthorization, async (c) => {
	assertSessionAuthenticated(c, 'approve CLI device logins');
	preventCaching(c);
	const deps = c.get('deps');
	const user = c.get('user');
	assertUserCodePreviewAllowed(user.id);
	const preview = await deps.services.cliAuthorizations.previewDevice(
		c.req.valid('param').userCode,
	);
	if (preview.status === 'scoped') {
		await assertTokenGrantProjectsVisible(deps, user, preview.requestedGrant);
	}
	return c.json(
		{
			success: true as const,
			data:
				preview.status === 'scoped'
					? {
							status: 'scoped' as const,
							requested_grant: preview.requestedGrant,
							expires_at: preview.expiresAt,
						}
					: { status: 'legacy' as const, expires_at: preview.expiresAt },
		},
		200,
	);
});

app.openapi(approveScopedDeviceAuthorization, async (c) => {
	assertSessionAuthenticated(c, 'approve CLI device logins');
	const deps = c.get('deps');
	const user = c.get('user');
	assertUserCodeAttemptAllowed(user.id);
	const body = c.req.valid('json');
	const preview = await deps.services.cliAuthorizations.previewDevice(body.user_code);
	if (preview.status !== 'scoped') {
		throw new BadRequestError('CLI authorization code is invalid or expired');
	}
	await assertTokenGrantProjectsVisible(deps, user, preview.requestedGrant);
	await assertTokenGrantProjectsVisible(deps, user, body.grant);
	const approved = await deps.services.cliAuthorizations.approveDeviceScoped(
		body.user_code,
		{
			tokenName: body.token_name,
			expiresInDays: body.expires_in_days,
			grant: body.grant,
		},
		user.id,
	);
	preventCaching(c);
	return c.json({ success: true as const, data: { expires_at: approved.expiresAt } }, 200);
});

export const cliTokenApp = createApp();

cliTokenApp.openapi(requestDeviceAuthorization, async (c) => {
	assertDeviceRequestAllowed();
	const requested = await c
		.get('deps')
		.services.cliAuthorizations.requestDevice(c.req.valid('json').code_challenge);
	preventCaching(c);
	return c.json(
		{
			success: true as const,
			data: deviceAuthorizationData(c, requested),
		},
		200,
	);
});

cliTokenApp.openapi(requestScopedDeviceAuthorization, async (c) => {
	assertDeviceRequestAllowed();
	const body = c.req.valid('json');
	const requested = await c
		.get('deps')
		.services.cliAuthorizations.requestDeviceScoped(body.code_challenge, body.grant);
	preventCaching(c);
	return c.json(
		{
			success: true as const,
			data: deviceAuthorizationData(c, requested),
		},
		200,
	);
});

cliTokenApp.openapi(pollDeviceAuthorization, async (c) => {
	const body = c.req.valid('json');
	assertDevicePollAllowed(body.device_code);
	const result = await c
		.get('deps')
		.services.cliAuthorizations.pollDevice(body.device_code, body.code_verifier);
	preventCaching(c);
	if (result.status === 'pending') {
		return c.json(
			{ success: true as const, data: { status: 'authorization_pending' as const } },
			202,
		);
	}
	await auditTokenCreation(c, result.credential);
	return c.json({ success: true as const, data: { token: result.credential.token } }, 200);
});

cliTokenApp.openapi(exchangeAuthorization, async (c) => {
	const body = c.req.valid('json');
	assertExchangeAllowed(body.code);
	const credential = await c
		.get('deps')
		.services.cliAuthorizations.exchange(body.code, body.code_verifier);
	await auditTokenCreation(c, credential);
	preventCaching(c);
	return c.json({ success: true as const, data: { token: credential.token } }, 200);
});

export default app;
