[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.32.0"
ci = ["github"]
allow-dirty = ["ci", "msi"]
targets = [
	"aarch64-apple-darwin",
	"aarch64-unknown-linux-gnu",
	"x86_64-apple-darwin",
	"x86_64-pc-windows-msvc",
	"x86_64-unknown-linux-gnu",
]
installers = ["shell", "powershell", "homebrew", "msi", "npm"]
include = ["generated/completions", "generated/man"]
install-path = "~/.local/bin"
install-updater = true
npm-scope = "@marimo-team"
npm-package = "mohub"
tap = "marimo-team/homebrew-tap"
unix-archive = ".tar.gz"

[dist.min-glibc-version]
x86_64-unknown-linux-gnu = "2.28"
